---
name: Run tests and lint with golangci-lint
on: [push]
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Clean
        run: make clean

      - name: Lint
        uses: DefectDojo-Inc/lint-action@master
        with:
          go-version: '1.21'
